import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Heebo } from 'next/font/google';
import Footer from '@/components/Footer';

const heebo = Heebo({ 
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Home page',
  description: 'Generated by John',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        <Header />
        <main className="main">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
